-- MLFV_AUXNOTAFISCALINCONS

-- Adicionado por Giuliano em 17/03/26
-- Ticket 703092

SELECT  /*+OPTIMIZER_FEATURES_ENABLE('11.2.0.4')*/
          DISTINCT (A.SEQAUXNOTAFISCAL) AS SEQAUXNOTAFISCAL,
          A.NUMERONF,
          A.NROEMPRESA,
          0 AS SEQAUXNFITEM,
          'B' AS BLOQAUTOR,
          103 AS CODINCONSISTENC,
          'CGO 2 não permite utilização com item de finalidade '||FF.DESCRICAO||'. Verifique! Item: ' ||XI.SEQPRODUTO MENSAGEM

  FROM CONSINCO.MLF_AUXNOTAFISCAL A INNER JOIN MLF_AUXNFITEM XI ON XI.SEQAUXNOTAFISCAL = A.SEQAUXNOTAFISCAL
                                    INNER JOIN MAP_PRODUTO P ON P.SEQPRODUTO = XI.SEQPRODUTO
                                    INNER JOIN MAP_FAMDIVISAO F ON F.SEQFAMILIA = P.SEQFAMILIA
                                    INNER JOIN MAP_FINALIDADEFAMILIA FF ON FF.FINALIDADEFAMILIA = F.FINALIDADEFAMILIA

 WHERE 1=1
   AND A.CODGERALOPER = 2
   AND F.FINALIDADEFAMILIA NOT IN ('U','O','A');
