CREATE OR REPLACE FUNCTION NAGF_BUSCA_MODFRETE (psChaveNF VARCHAR2) 

RETURN NUMBER IS 
  psModFrete NUMBER;
  
 BEGIN

  SELECT MAX(NVL(fBuscaTipoFreteTransp(A.SEQNOTAFISCAL,A.NROCARGA,A.NROEMPRESA,A.TIPOFRETE,A.SEQTRANSPORTADOR),0))
    INTO psModFrete
    FROM MFLV_BASENF A
   WHERE A.nfechaveacesso = psChaveNF;

 RETURN psModFrete;
 
 END;
