CREATE OR REPLACE FUNCTION NAGF_STATUS_TIT_FIN (psSeqTITULO NUMBER)

  RETURN NUMBER IS
   psTitAut     NUMBER(10);

  BEGIN

   SELECT COUNT(1)
     INTO psTitAut
     FROM FI_AUTPAGTO X
    WHERE X.SEQTITULO = psSeqTitulo
      AND 1=1;

RETURN psTitAut;

END;
