CREATE OR REPLACE FUNCTION NAGF_BUSCASEQREC (psCodigo varchar2)

  RETURN varchar2 IS

  seqRec varchar2(10);

  BEGIN

 SELECT MAX(SEQITEM)
   INTO seqRec
   FROM RF_TABAUXPCITENS X 
	 WHERE X.SEQTABAUX IN (6,9)
	 AND X.CODIGO = psCodigo;

  RETURN seqRec;

  END;
