CREATE OR REPLACE PROCEDURE NAGP_CANCELA_PEDVENDA (psNroPedVenda NUMBER) AS

BEGIN
  
    UPDATE CONSINCO.MAD_PEDVENDAITEM B
       SET B.QTDATENDIDA = 0
     WHERE B.NROPEDVENDA = psNroPedVenda;
  
    UPDATE CONSINCO.MAD_PEDVENDA
       SET SITUACAOPED     = 'L'
     WHERE NROPEDVENDA = psNroPedVenda
       AND SITUACAOPED NOT IN ('F','L');

    UPDATE CONSINCO.MAD_PEDVENDA
       SET SITUACAOPED     = 'C',
           DTACANCELAMENTO = SYSDATE,
           USUCANCELAMENTO = 'PROC_MANUAL',
           MOTCANCELAMENTO = 'Solic GLPI - Proc NAGP_CANCELA_PEDVENDA',
           OBSCANCELAMENTO = 'NAGP_CANCELA_PEDVENDA',
           INDREPLICAFV    = 'S'
     WHERE NROPEDVENDA = psNroPedVenda;

  COMMIT;
END;
