CREATE OR REPLACE PROCEDURE NAGP_UPD_FORNECDIVISAO (psSeqFornecedor NUMBER) AS

BEGIN
  
  UPDATE MAF_FORNECDIVISAO X
     SET INDINDENIZAVARIA      = NULL,
         NROREGTRIBUTACAO      = 0,
         NROCONDPAGDEV         = 21,
         INDCALCFRETECUSTODESC = 'S',
         INDCALCDESPCUSTODESC  = 'S',
         INDSOMAFRETETOTALNF   = 'S',
         INDSOMADESPTOTALNF    = 'S',
         INDSOMAFRETEBASEIPI   = 'S',
         INDSOMADESPBASEIPI    = 'S',
         INDCONSISTENCMXML     = 'S',
         X.USUALTERACAO        = 'PORTAL_FOR',
         X.DTAALTERACAO        = SYSDATE
   WHERE X.SEQFORNECEDOR = psSeqFornecedor;
   
   UPDATE GE_PESSOA G SET G.GRUPO = 'FORNECEDORES', G.USUALTERACAO = 'PORTAL_FOR', G.DTAALTERACAO = SYSDATE
    WHERE SEQPESSOA = psSeqFornecedor;
   
   COMMIT;
   
END;
