CREATE OR REPLACE PROCEDURE NAGP_TROCA_FAMILIA AS

 psQtdPendente NUMBER(10);

BEGIN

SELECT COUNT(1)
  INTO psQtdPendente
  FROM MAP_ALTERAFAMILIAPRODUTO
 WHERE DTAALTERACAO >= TRUNC(SYSDATE)
   AND INDALTERACAO = 'P';
   
   IF psQtdPendente > 0 THEN

  CONSINCO.PKG_ADM_PRODUTO.SP_TROCAFAMILIASJOB('S');

   END IF;
   
END;
