CREATE OR REPLACE PROCEDURE NAGP_PALIATIVO_CBS_IBS_DEV_TOT IS

  -- Paliativo Giuliano para reforma
  -- devolucao nota ref sem informacoes - Paliativo aguardando TOTVS  
  -- O paliat vai ate no max 31/03
  
  psData DATE;
  
BEGIN
  
  SELECT TRUNC(SYSDATE) INTO psData FROM DUAL;
  
  IF psData <= DATE '2026-03-31' THEN
  
  FOR rej IN 
    
  (SELECT /*+OPTIMIZER_FEATURES_ENABLE('11.2.0.4')*/ 
       N.SEQNOTAFISCAL, N.nroempresa, SEQNF
   FROM MLFV_BASENFE N INNER JOIN (SELECT DESCRICAO, SEQNOTAFISCAL, ROW_NUMBER() OVER(PARTITION BY SEQNOTAFISCAL ORDER BY DTALOG DESC) RN
                                     FROM MFL_NFELOG L WHERE 1=1 AND L.DESCRICAO LIKE '%CBS difere da soma dos itens%' ORDER BY L.DTALOG DESC) L ON L.SEQNOTAFISCAL = N.SEQNOTAFISCAL AND L.RN = 1
                       INNER JOIN (SELECT DESCRICAO, SEQNOTAFISCAL, ROW_NUMBER() OVER(PARTITION BY SEQNOTAFISCAL ORDER BY DTALOG DESC) RN
                                     FROM MFL_NFELOG L WHERE 1=1 AND L.DESCRICAO LIKE '%%' ORDER BY L.DTALOG DESC) U ON U.SEQNOTAFISCAL = N.SEQNOTAFISCAL AND U.RN = 1
                WHERE 1 = 1
                  AND N.STATUSNFE = 5
                  AND     EXISTS (SELECT 1 FROM MFL_NFELOG A WHERE A.SEQNOTAFISCAL = N.SEQNOTAFISCAL AND A.DESCRICAO LIKE '%CBS difere da soma dos itens%')
                  AND NOT EXISTS (SELECT 2 FROM MFL_NFELOG B WHERE B.SEQNOTAFISCAL = N.SEQNOTAFISCAL AND B.DESCRICAO LIKE '%Autoriz%')
                  AND N.DTAEMISSAO >= SYSDATE - 5

      AND NOT EXISTS (SELECT 1 FROM NAGT_PALIAT_DEV D WHERE D.SEQNF = N.SEQNF AND MOT = 'Total CBS/IBS')
      
   UNION
   SELECT /*+OPTIMIZER_FEATURES_ENABLE('11.2.0.4')*/ 
       N.SEQNOTAFISCAL, N.nroempresa, SEQNF
   FROM MLFV_BASENFE N INNER JOIN (SELECT DESCRICAO, SEQNOTAFISCAL, ROW_NUMBER() OVER(PARTITION BY SEQNOTAFISCAL ORDER BY DTALOG DESC) RN
                                     FROM MFL_NFELOG L WHERE 1=1 AND L.DESCRICAO LIKE '%Depois desta, faltou uma da%' ORDER BY L.DTALOG DESC) L ON L.SEQNOTAFISCAL = N.SEQNOTAFISCAL AND L.RN = 1
                       INNER JOIN (SELECT DESCRICAO, SEQNOTAFISCAL, ROW_NUMBER() OVER(PARTITION BY SEQNOTAFISCAL ORDER BY DTALOG DESC) RN
                                     FROM MFL_NFELOG L WHERE 1=1 AND L.DESCRICAO LIKE '%%' ORDER BY L.DTALOG DESC) U ON U.SEQNOTAFISCAL = N.SEQNOTAFISCAL AND U.RN = 1
                WHERE 1 = 1
                  AND N.STATUSNFE = 99
                  AND     EXISTS (SELECT 1 FROM MFL_NFELOG A WHERE A.SEQNOTAFISCAL = N.SEQNOTAFISCAL AND A.DESCRICAO LIKE '%Depois desta, faltou uma da%')
                  AND NOT EXISTS (SELECT 2 FROM MFL_NFELOG B WHERE B.SEQNOTAFISCAL = N.SEQNOTAFISCAL AND B.DESCRICAO LIKE '%Autoriz%')
                  AND N.DTAEMISSAO >= SYSDATE - 5

      AND NOT EXISTS (SELECT 1 FROM NAGT_PALIAT_DEV D WHERE D.SEQNF = N.SEQNF AND MOT = 'Total CBS/IBS'))
    
  LOOP
  
  INSERT INTO NAGT_PALIAT_DEV VALUES (rej.SEQNF, 'Total CBS/IBS');
 
  COMMIT;
  
  UPDATE MAX_EMPRESANOTATECNICA NT SET NT.STATUS = 'I'
   WHERE NT.NROEMPRESA = rej.NROEMPRESA
     AND NT.NRONOTATECNICA = 2025002;
     
  SP_EXPORTANFE(rej.SEQNOTAFISCAL, 'E');
  
  UPDATE MAX_EMPRESANOTATECNICA NT SET NT.STATUS = 'A'
   WHERE NT.NROEMPRESA = rej.NROEMPRESA
     AND NT.NRONOTATECNICA = 2025002;

     COMMIT;
      
  END LOOP;
  
  END IF;
  
 EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Error Code: ' || SQLCODE);
        DBMS_OUTPUT.PUT_LINE('Error Message: ' || SQLERRM);
        DBMS_OUTPUT.PUT_LINE('Error Stack: ' || DBMS_UTILITY.FORMAT_ERROR_STACK);
        DBMS_OUTPUT.PUT_LINE('Error Backtrace: ' || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE);
        DBMS_OUTPUT.PUT_LINE('Call Stack: ' || DBMS_UTILITY.FORMAT_CALL_STACK);
     -- DBMS para nao estourar erro SQL caso outro problema surja ao rodar essa proc, nao para o processo

END;
