CREATE OR REPLACE PROCEDURE NAGP_PALIATIVO_CBS_IBS_DEV_TOT_v2 IS

  -- Paliativo Giuliano para reforma
  -- devolucao nota ref sem informacoes - Paliativo aguardando TOTVS  
  -- O paliat vai ate no max 31/08 -- Configurado no primeiro IF
  
  psData DATE;
  
BEGIN
  
  SELECT TRUNC(SYSDATE) INTO psData FROM DUAL;
  
  IF 1=1 AND psData <= DATE '2026-08-31' THEN
  
  --======= Pega as notas rejeitadas =======--
  
  FOR rej IN 
    
  (SELECT /*+OPTIMIZER_FEATURES_ENABLE('11.2.0.4')*/ 
       N.SEQNOTAFISCAL, N.nroempresa, SEQNF
   FROM MLFV_BASENFE N INNER JOIN (SELECT DESCRICAO, SEQNOTAFISCAL, ROW_NUMBER() OVER(PARTITION BY SEQNOTAFISCAL ORDER BY DTALOG DESC) RN
                                     FROM MFL_NFELOG L WHERE 1=1 AND L.DESCRICAO LIKE '%CBS difere da soma dos itens%' ORDER BY L.DTALOG DESC) L ON L.SEQNOTAFISCAL = N.SEQNOTAFISCAL AND L.RN = 1
                       INNER JOIN (SELECT DESCRICAO, SEQNOTAFISCAL, ROW_NUMBER() OVER(PARTITION BY SEQNOTAFISCAL ORDER BY DTALOG DESC) RN
                                     FROM MFL_NFELOG L WHERE 1=1 AND L.DESCRICAO LIKE '%%' ORDER BY L.DTALOG DESC) U ON U.SEQNOTAFISCAL = N.SEQNOTAFISCAL AND U.RN = 1
                WHERE 1 = 1
                  AND N.STATUSNFE = 5
                  AND     EXISTS (SELECT 1 FROM MFL_NFELOG A WHERE A.SEQNOTAFISCAL = N.SEQNOTAFISCAL AND A.DESCRICAO LIKE '%CBS difere da soma dos itens%')
                  AND NOT EXISTS (SELECT 2 FROM MFL_NFELOG B WHERE B.SEQNOTAFISCAL = N.SEQNOTAFISCAL AND B.DESCRICAO LIKE '%Autoriz%')
                  AND NOT EXISTS (SELECT 2 FROM MFL_NFELOG C WHERE C.SEQNOTAFISCAL = N.SEQNOTAFISCAL AND C.DESCRICAO LIKE '%indevido%' 
                                     AND C.DTALOG > SYSDATE - INTERVAL '1' HOUR - INTERVAL '10' MINUTE) 
                  AND N.DTAEMISSAO >= SYSDATE - 10

      AND (SELECT COUNT(1) FROM NAGT_PALIAT_DEV D WHERE D.SEQNF = N.SEQNF AND MOT = 'Total CBS/IBS') < 6
      
   UNION
   SELECT /*+OPTIMIZER_FEATURES_ENABLE('11.2.0.4')*/ 
       N.SEQNOTAFISCAL, N.nroempresa, SEQNF
   FROM MLFV_BASENFE N INNER JOIN (SELECT DESCRICAO, SEQNOTAFISCAL, ROW_NUMBER() OVER(PARTITION BY SEQNOTAFISCAL ORDER BY DTALOG DESC) RN
                                     FROM MFL_NFELOG L WHERE 1=1 AND L.DESCRICAO LIKE '%Depois desta, faltou uma da%' ORDER BY L.DTALOG DESC) L ON L.SEQNOTAFISCAL = N.SEQNOTAFISCAL AND L.RN = 1
                       INNER JOIN (SELECT DESCRICAO, SEQNOTAFISCAL, ROW_NUMBER() OVER(PARTITION BY SEQNOTAFISCAL ORDER BY DTALOG DESC) RN
                                     FROM MFL_NFELOG L WHERE 1=1 AND L.DESCRICAO LIKE '%%' ORDER BY L.DTALOG DESC) U ON U.SEQNOTAFISCAL = N.SEQNOTAFISCAL AND U.RN = 1
                WHERE 1 = 1
                  AND N.STATUSNFE = 99
                  AND     EXISTS (SELECT 1 FROM MFL_NFELOG A WHERE A.SEQNOTAFISCAL = N.SEQNOTAFISCAL AND A.DESCRICAO LIKE '%Depois desta, faltou uma da%')
                  AND NOT EXISTS (SELECT 2 FROM MFL_NFELOG B WHERE B.SEQNOTAFISCAL = N.SEQNOTAFISCAL AND B.DESCRICAO LIKE '%Autoriz%')
                  AND NOT EXISTS (SELECT 2 FROM MFL_NFELOG C WHERE C.SEQNOTAFISCAL = N.SEQNOTAFISCAL AND C.DESCRICAO LIKE '%indevido%' 
                                     AND C.DTALOG > SYSDATE - INTERVAL '1' HOUR - INTERVAL '10' MINUTE) 
                  AND N.DTAEMISSAO >= SYSDATE - 10

      AND (SELECT COUNT(1) FROM NAGT_PALIAT_DEV D WHERE D.SEQNF = N.SEQNF AND MOT = 'Total CBS/IBS') < 6
      )
    
  LOOP
 
  --======= Insere o seq na tabela de controle =======--

 INSERT INTO NAGT_PALIAT_DEV VALUES (rej.SEQNF, 'Total CBS/IBS');
 
 COMMIT;
    
   --======= Trata os itens sem informação dos trbutos =======--

 FOR item IN (
 
 SELECT CC.PERALIQCBS, CC.PERALIQREDCBS, CC.CSTCBS, CC.CCLASSTRIBCBS,
        CC.PERALIQIBSUF, CC.PERALIQREDIBSUF, CC.CSTIBSUF, CC.CCLASSTRIBIBSUF,
        CC.PERALIQIBSMUN, CC.PERALIQREDIBSMUN, CC.CSTIBSMUN, CC.CCLASSTRIBIBSMUN,
        ROUND((CC.PERALIQCBS * (1-CC.PERALIQREDCBS/100)),2) PERALIQEFETCBS,
        ROUND((CC.PERALIQIBSUF * (1-CC.PERALIQREDIBSUF/100)),2) PERALIQEFETIBSUF,
        ROUND((CC.PERALIQIBSMUN * (1-CC.PERALIQREDIBSMUN/100)),2) PERALIQEFETIBSMUN,
        XI.SEQPRODUTO   
        
   FROM NAGV_PDV_CCT CC INNER JOIN MLF_NFITEM XI ON XI.SEQPRODUTO = CC.SEQPRODUTO
  WHERE XI.SEQNF = rej.SEQNF)
    
 LOOP
   
  UPDATE MLF_NFITEM XI
     SET XI.PERALIQCBS         = item.PerAliqCBS,
         XI.PERALIQREDCBS      = item.PerAliqRedCBS,
         XI.CSTCBS             = item.CSTCBS,
         XI.CCLASSTRIBCBS      = item.CClassTribCBS,
         XI.PERALIQIBSUF       = item.PerAliqIBSUF,
         XI.PERALIQREDIBSUF    = item.PerAliqRedIBSUF,
         XI.CSTIBSUF           = item.CSTIBSUF,
         XI.CCLASSTRIBIBSUF    = item.CClassTribIBSUF,
         XI.PERALIQIBSMUN      = item.PerAliqIBSMUN,
         XI.PERALIQREDIBSMUN   = item.PerAliqRedIBSMUN,
         XI.CSTIBSMUN          = item.CSTIBSMUN,
         XI.CCLASSTRIBIBSMUN   = item.CClassTribIBSMUN,
         
         --=== Aliqutoas efetivas ===--
         XI.PERALIQEFETIVACBS  = item.Peraliqefetcbs,
         XI.PERALIQEFETIVAIBSMUN = item.Peraliqefetibsmun,
         XI.PERALIQEFETIVAIBSUF  = item.Peraliqefetibsuf,
         
         --=== Ajusta bases zeradas ===--
         XI.VLRBASECBS    = NVL(XI.VLRBASECBS, XI.VLRITEM),
         XI.VLRBASEIBSUF  = NVL(XI.VLRBASEIBSUF, XI.VLRITEM),
         XI.VLRBASEIBSMUN = NVL(XI.VLRBASEIBSMUN, XI.VLRITEM),
         
         --=== Valores de impostos ===--
         
         XI.VLRIMPOSTOCBS = CASE WHEN XI.VLRIMPOSTOCBS IS NULL
                            THEN ROUND(NVL(XI.VLRBASECBS, XI.VLRITEM) * (NVL(XI.PERALIQEFETIVACBS,0) / 100), 2)
                            ELSE XI.VLRIMPOSTOCBS END,

         XI.VLRIMPOSTOIBSUF = CASE WHEN XI.VLRIMPOSTOIBSUF IS NULL
                              THEN ROUND(NVL(XI.VLRBASEIBSUF, XI.VLRITEM) * (NVL(XI.PERALIQEFETIVAIBSUF,0) / 100), 2)
                              ELSE XI.VLRIMPOSTOIBSUF END,

         XI.VLRIMPOSTOIBSMUN = CASE WHEN XI.VLRIMPOSTOIBSMUN IS NULL
                               THEN ROUND(NVL(XI.VLRBASEIBSMUN, XI.VLRITEM) * (NVL(XI.PERALIQEFETIVAIBSMUN,0) / 100), 2)
                               ELSE XI.VLRIMPOSTOIBSMUN END
         
   WHERE XI.SEQNF = rej.SEQNF
     AND XI.SEQPRODUTO = item.SEQPRODUTO;
  
   --======= Recalcula quando existe redução na base =======--

  UPDATE MLF_NFITEM XI
   SET XI.VLRIMPOSTOIBSUF =
         CASE
           WHEN NVL(XI.PERALIQREDIBSUF,0) = 100 THEN 0
           ELSE ROUND(
                  XI.VLRBASEIBSUF *
                  ((XI.PERALIQIBSUF *
                   (1 - NVL(XI.PERALIQREDIBSUF,0) / 100)
                  ) / 100)
                , 2)
         END,
       XI.VLRIMPOSTOCBS =
         CASE
           WHEN NVL(XI.PERALIQREDCBS,0) = 100 THEN 0
           ELSE ROUND(
                  XI.VLRBASECBS *
                  ((XI.PERALIQCBS *
                   (1 - NVL(XI.PERALIQREDCBS,0) / 100)
                  ) / 100)
                , 2)
         END,
     
     --======= Corrige o tamanho do cClassTrib para 6 digitos =======--

     XI.CCLASSTRIBIBSMUN = CASE WHEN LENGTH(CCLASSTRIBIBSMUN) = 1 THEN LPAD(CCLASSTRIBIBSMUN,6,'0') ELSE CCLASSTRIBIBSMUN END,
     XI.CCLASSTRIBIBSUF  = CASE WHEN LENGTH(CCLASSTRIBIBSUF) = 1 THEN LPAD(CCLASSTRIBIBSUF,6,'0') ELSE CCLASSTRIBIBSUF END,
     XI.CCLASSTRIBCBS    = CASE WHEN LENGTH(CCLASSTRIBCBS) = 1 THEN LPAD(CCLASSTRIBCBS,6,'0') ELSE CCLASSTRIBCBS END,
     XI.CCLASSTRIBIS     = CASE WHEN LENGTH(CCLASSTRIBIS) = 1 THEN LPAD(CCLASSTRIBIS,6,'0') ELSE CCLASSTRIBIS END
     
 WHERE XI.SEQNF = rej.SEQNF
   AND XI.SEQPRODUTO = item.SEQPRODUTO;
  
  COMMIT;
  
  END LOOP;
      
  -- Exporta a nota novamente
  SP_EXPORTANFE(rej.SEQNOTAFISCAL, 'E');
      
  COMMIT;
  END LOOP;
  
  END IF;
  
 EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Error Code: ' || SQLCODE);
        DBMS_OUTPUT.PUT_LINE('Error Message: ' || SQLERRM);
        DBMS_OUTPUT.PUT_LINE('Error Stack: ' || DBMS_UTILITY.FORMAT_ERROR_STACK);
        DBMS_OUTPUT.PUT_LINE('Error Backtrace: ' || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE);
        DBMS_OUTPUT.PUT_LINE('Call Stack: ' || DBMS_UTILITY.FORMAT_CALL_STACK);
     -- DBMS para nao estourar erro SQL caso outro problema surja ao rodar essa proc, nao para o processo

END;
