CREATE TABLE NAGT_CONTROLE_SELOS_PDV_LOG
(    
    NROEMPRESA       VARCHAR2(10),
    NROCHECKOUT      NUMBER,
    SEQTURNO         NUMBER,
    DTAMOVIMENTO     DATE,
    
    SELO_INICIAL VARCHAR2(50),
    SELO_FINAL   VARCHAR2(50),
    DIFERENCA    NUMBER,
    
    USUARIO_LOG      VARCHAR2(200),
    DATA_LOG         DATE,
    OPERACAO         VARCHAR2(20)
);
