CREATE OR REPLACE TRIGGER NAGTRG_LOG_GE_CONSULTA
BEFORE UPDATE OF INSTRUCAOSQL OR DELETE ON GE_CONSULTA
FOR EACH ROW
BEGIN
    CONSINCO.NAGP_LOG_GE_CONSULTA(          -- chame com o schema se necessário
        :OLD.SEQCONSULTA,
        CASE 
            WHEN UPDATING THEN 'Update'
            WHEN DELETING THEN 'Delete'
        END
    );
END;
