CREATE TABLE NAGT_GE_CONSULTA_LOG (
    ID_LOG            NUMBER GENERATED ALWAYS AS IDENTITY,
    SEQCONSULTA       NUMBER NOT NULL,
    CAMPO_ALTERADO    VARCHAR2(100),
    VALOR_ANTIGO      CLOB,
    USUARIO_ALTERACAO VARCHAR2(100),
    DATA_ALTERACAO    DATE,
    TIPO_OPERACAO     VARCHAR2(10)
);

SELECT * FROM NAGT_GE_CONSULTA_LOG
