CREATE OR REPLACE TRIGGER NAGTR_MRL_EMPSOFTPDV_LOG
BEFORE UPDATE ON CONSINCO.MRL_EMPSOFTPDV
FOR EACH ROW

DECLARE
    V_USUALTERACAO VARCHAR2(100);
BEGIN

    SELECT USER
      INTO V_USUALTERACAO
      FROM DUAL;

    INSERT INTO CONSINCO.NAGT_MRL_EMPSOFTPDV_LOG
    (
        NROEMPRESA,
        SOFTPDV,
        DIRETIMPORTARQUIVO,
        DIRETEXPORTARQUIVO,
        TIPOEXPORTACAO,
        DIRETTEMP,
        NOMEVIEW,
        TIPOCARGA,
        TIPOSOFT,
        STATUS,
        DTAALTERACAO,
        USUALTERACAO,
        DTAIMPORTEXPORT,
        USUIMPORTEXPORT,
        NROGONDOLA,
        SEQEXPORTACAO,
        DIRETDESTINO,
        TIPODADOLINHA,
        NROCARGAPDV,
        INDCORTADIGBALANCA,
        INDDESCBALANCA,
        DIRETEXPORTARQPRECOPROMOC,
        INDGERATXTNFE,
        SUFIXO_ARQUIVO_EDI,
        NOMEQRPETIQUETA,
        QTDCOLUNASETIQ,
        PREFIXO_ARQUIVO_EDI,
        VERSAOLAYOUT,
        NOMEJOBNFE,
        NOMEJOBMDFE,
        INDETIQWEB,
        NOMEVIEWETIQWEB,
        NOMEIMPETIQWEB,
        NOMEJOBNFSE,
        INDUSUARIOFTPBALANCA,
        DIRETIMPORTADOS,
        DIRETREJEITADOS,
        SEQETIQUETALAYOUT,
        TIPOQUEBRALINHA,
        XMLTEMPLATERELETIQWEB,
        NOMEJOBMANIFESTACAOCTE,
        USUARIO_LOG,
        DATA_LOG
    )
    VALUES
    (
        :OLD.NROEMPRESA,
        :OLD.SOFTPDV,
        :OLD.DIRETIMPORTARQUIVO,
        :OLD.DIRETEXPORTARQUIVO,
        :OLD.TIPOEXPORTACAO,
        :OLD.DIRETTEMP,
        :OLD.NOMEVIEW,
        :OLD.TIPOCARGA,
        :OLD.TIPOSOFT,
        :OLD.STATUS,
        :OLD.DTAALTERACAO,
        :OLD.USUALTERACAO,
        :OLD.DTAIMPORTEXPORT,
        :OLD.USUIMPORTEXPORT,
        :OLD.NROGONDOLA,
        :OLD.SEQEXPORTACAO,
        :OLD.DIRETDESTINO,
        :OLD.TIPODADOLINHA,
        :OLD.NROCARGAPDV,
        :OLD.INDCORTADIGBALANCA,
        :OLD.INDDESCBALANCA,
        :OLD.DIRETEXPORTARQPRECOPROMOC,
        :OLD.INDGERATXTNFE,
        :OLD.SUFIXO_ARQUIVO_EDI,
        :OLD.NOMEQRPETIQUETA,
        :OLD.QTDCOLUNASETIQ,
        :OLD.PREFIXO_ARQUIVO_EDI,
        :OLD.VERSAOLAYOUT,
        :OLD.NOMEJOBNFE,
        :OLD.NOMEJOBMDFE,
        :OLD.INDETIQWEB,
        :OLD.NOMEVIEWETIQWEB,
        :OLD.NOMEIMPETIQWEB,
        :OLD.NOMEJOBNFSE,
        :OLD.INDUSUARIOFTPBALANCA,
        :OLD.DIRETIMPORTADOS,
        :OLD.DIRETREJEITADOS,
        :OLD.SEQETIQUETALAYOUT,
        :OLD.TIPOQUEBRALINHA,
        :OLD.XMLTEMPLATERELETIQWEB,
        :OLD.NOMEJOBMANIFESTACAOCTE,
        V_USUALTERACAO,
        SYSDATE
    );

END;
