CREATE OR REPLACE VIEW NAGV_PDV_CCT AS
WITH BCIDADE AS (
 SELECT CID.UF, CID.CODIBGE, CID.CIDADE
 FROM MAX_EMPRESA EMP
   JOIN GE_PESSOA P
     ON EMP.SEQPESSOAEMP = P.SEQPESSOA
   JOIN GE_CIDADE CID
     ON P.SEQCIDADE = CID.SEQCIDADE
  WHERE EMP.STATUS = 'A' AND EMP.NROEMPRESA = 1
  GROUP BY CID.UF, CID.CODIBGE, CID.CIDADE),
   BASE AS (
 SELECT PROD.SEQPRODUTO,FAM.SEQFAMILIA, FAM.CODNBMSH NCM, CID.UF, CID.CODIBGE, CID.CIDADE
   FROM MAP_PRODUTO PROD
   JOIN MAP_FAMILIA FAM
     ON PROD.SEQFAMILIA = FAM.SEQFAMILIA
  CROSS JOIN BCIDADE CID
  ORDER BY PROD.SEQPRODUTO, CID.UF, CID.CODIBGE
   )
SELECT  "SEQPRODUTO","SEQFAMILIA","NCM","UF","CODIBGE","CIDADE","CENARIOCBS","PERALIQCBS","PERALIQREDCBS","PERALIQCCREDPRESCBS","PERALIQREDCCREDPRESCBS","CSTCBS","CCLASSTRIBCBS","CCREDPRESCBS","MSGERROCBS","CENARIOIBSUF","PERALIQIBSUF","PERALIQREDIBSUF","PERALIQCCREDPRESIBSUF","PERALIQREDCCREDPRESIBSUF","CSTIBSUF","CCLASSTRIBIBSUF","CCREDPRESIBSUF","MSGERROIBSUF","CENARIOIBSMUN","PERALIQIBSMUN","PERALIQREDIBSMUN","CSTIBSMUN","CCLASSTRIBIBSMUN","MSGERROIBSMUN","CENARIOIS","PERALIQIS","PERALIQREDIS","CSTIS","CCLASSTRIBIS","MSGERROIS"
   FROM BASE B
  CROSS JOIN TABLE(
        PKG_CCTMOTOR.CCTF_BUSCACENARIO(
                                       psProduto             => B.SEQPRODUTO,
                                       psFamilia             => B.SEQFAMILIA,
                                       psNCM                 => B.NCM,
                                       psUfDestino           => B.UF,
                                       psCodIBGE             => B.CODIBGE
                                    )
  ) IMP;
