CREATE OR REPLACE VIEW NAGV_BASE_REGUA_COBRANCA_PRETAE AS

SELECT Initcap(ACO.DESCACORDO) DESCACORDO, ACO.NROACORDO, F.DTAVENCIMENTO, F.NROPARCELA||'/'||F.QTDPARCELA PARCELA,
       'R$ '||TO_CHAR(F.VLRORIGINAL, 'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''') VLR_ACO,
       'R$ '||TO_CHAR(F.VLRORIGINAL - F.VLRPAGO, 'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''') VLR_PARC_ABERTO,
       F.DTAVENCIMENTO - TRUNC(SYSDATE) DIAS_ATE_VENC,
       (SELECT LISTAGG(FF.EMAILACORDO, '; ') WITHIN GROUP (ORDER BY SEQFORNECEDOR) FROM MAF_FORNECEDOR FF WHERE FF.SEQFORNECEDOR = F.SEQPESSOA
           AND TRIM(FF.EMAILACORDO) IS NOT NULL AND UPPER(EMAILACORDO) NOT LIKE '%NAG%' AND UPPER(EMAILACORDO) NOT LIKE '%SCANN%')  EMAIL_REP,
       CASE WHEN AC.CODTIPOACORDO = 1 THEN 'ACORDO COMERCIAL' ELSE AC.DESCRICAO END TIP_ACORDO, F.SEQPESSOA COD_FORNECEDOR, CO.COMPRADOR,
       INITCAP(G.NOMERAZAO) NOME_REPRES,
       fEmailFinFornec(ACO.SEQFORNECEDOR) EMAIL_FIN_FORNEC, ACO.SEQCOMPRADOR COD_COMPRADOR, G.NOMERAZAO FORNECEDOR,
       --Criando indexes para regra na regua de cobranca
       1 + (SELECT COUNT(1) FROM NAGT_LOG_ENVIO_ACO_EMAIL XX WHERE XX.NRO_ACORDO = F.NROTITULO) NIVEL_REGUA
       --
  FROM FI_TITULO F INNER JOIN MAC_TIPOACORDO AC ON AC.CODESPECIE = F.CODESPECIE
                   INNER JOIN GE_PESSOA G ON G.SEQPESSOA = F.SEQPESSOA
                   INNER JOIN MSU_ACORDOPROMOC ACO ON ACO.NROACORDO = F.NROTITULO AND ACO.SEQFORNECEDOR = F.SEQPESSOA AND ACO.CODTIPOACORDO = AC.CODTIPOACORDO AND ACO.SITUACAOACORDO = 'F'
                   INNER JOIN MAX_COMPRADOR CO ON CO.SEQCOMPRADOR = ACO.SEQCOMPRADOR
 WHERE EXISTS( SELECT 1
                 FROM NAGT_BASE_REDE_REGUA X INNER JOIN GE_REDE R ON R.DESCRICAO = X.FORNECEDOR
                                             INNER JOIN GE_REDEPESSOA RP ON RP.SEQREDE = R.SEQREDE
                WHERE RP.SEQPESSOA = F.SEQPESSOA)
   AND NVL(AC.INDUTILINTEGRACAOASSELETRONICA, 'S') = 'S'
   AND F.ABERTOQUITADO = 'A'
   AND F.SITUACAO != 'C'
   AND NOT EXISTS -- evita duplicidade de envio no dia
       (SELECT 1 FROM NAGT_LOG_ENVIO_ACO_EMAIL XX WHERE XX.NRO_ACORDO = F.NROTITULO AND XX.DATA_ENVIO >= TRUNC(SYSDATE))
   AND NOT EXISTS -- remove TAE, sao enviados em paralelo
       (SELECT 2 FROM NAGV_TAE_ACORDOS_V4 RC WHERE RC.NRO_ACORDO = F.NROTITULO AND RC.COD_FORNECEDOR = F.SEQPESSOA);
