CREATE OR REPLACE VIEW NAGV_PRODNFE_SEMVINCULO AS

SELECT DISTINCT A.SEQPESSOA COD_FORNEC, G.NOMERAZAO RAZAOFORNEC, SUBSTR(NROCGCCPF,0,6) CGC_FORNEC, A.NUMERONF,
       A.NROEMPRESA, A.NFECHAVEACESSO CHAVENF, L.M014_CD_NCM NCM, L.M014_CD_PRODUTO REF_FORNEC

  FROM CONSINCO.MLF_AUXNOTAFISCAL A INNER JOIN CONSINCO.MLF_AUXNFITEM B ON A.SEQAUXNOTAFISCAL = B.SEQAUXNOTAFISCAL
                                    INNER JOIN TMP_M000_NF K ON (K.M000_NR_CHAVE_ACESSO = A.NFECHAVEACESSO)
                                    INNER JOIN TMP_M014_ITEM L ON (L.M000_ID_NF = K.M000_ID_NF AND L.M014_NR_ITEM = B.SEQITEMNFXML)
                                    INNER JOIN GE_PESSOA G ON G.SEQPESSOA = A.SEQPESSOA

 WHERE 1=1
  AND A.SEQPESSOA > 999
  AND A.DTAEMISSAO >= SYSDATE - 30
  AND NOT EXISTS (SELECT 1 FROM MAP_PRODCODIGO C  WHERE UPPER(C.CODACESSO) = UPPER(L.M014_CD_PRODUTO)  AND C.TIPCODIGO  = 'F' AND LPAD(NROCGCCPF,12,0)||LPAD(DIGCGCCPF,2,0) LIKE '%'||C.CGCFORNEC||'%')
  AND NOT EXISTS (SELECT 2 FROM MAP_PRODCODIGO C2 WHERE C2.CODACESSO = L.M014_CD_EAN     AND C2.TIPCODIGO = 'E' AND LPAD(NROCGCCPF,12,0)||LPAD(DIGCGCCPF,2,0) LIKE '%'||C2.CGCFORNEC||'%')
  
  UNION 

SELECT G.SEQPESSOA,  G.NOMERAZAO,  SUBSTR(G.NROCGCCPF,0,6) CGC_FORNEC,
       K.M000_NR_NF, F.SEQPESSOA,  K.M000_NR_CHAVE_ACESSO, L.M014_CD_NCM NCM, L.M014_CD_PRODUTO REF_FORNEC
  FROM TMP_M000_NF K INNER JOIN TMP_M014_ITEM L ON L.M000_ID_NF = K.M000_ID_NF
                     INNER JOIN TMP_M001_EMITENTE B ON B.M000_ID_NF = K.M000_ID_NF
                     INNER JOIN TMP_M002_DESTINATARIO D ON D.M000_ID_NF = K.M000_ID_NF
                     INNER JOIN GE_PESSOA G ON LPAD(G.NROCGCCPF, 12, '0') = SUBSTR(B.M001_NR_CNPJ, 1, Length(B.M001_NR_CNPJ)-2)
                     INNER JOIN GE_PESSOA F ON LPAD(F.NROCGCCPF, 12, '0') = SUBSTR(D.M002_NR_CNPJ_CPF, 1, Length(D.M002_NR_CNPJ_CPF)-2)
                     
 WHERE 1=1
   AND K.M000_DT_EMISSAO >= SYSDATE - 30
   AND G.SEQPESSOA > 999
   AND F.SEQPESSOA < 999
   AND NOT EXISTS (SELECT 1 FROM MAP_PRODCODIGO C WHERE UPPER(C.CODACESSO) = UPPER(L.M014_CD_PRODUTO) AND C.CGCFORNEC LIKE G.NROCGCCPF||'%'); 
 
SELECT * FROM NAGV_PRODNFE_SEMVINCULO X WHERE X.CHAVENF = 35260803491105000189550010001800171000142656 
