CREATE OR REPLACE VIEW NAGV_BASE_MRL_PROMOCESPECIAL_APP AS
SELECT (SELECT MAX(C.SEQPROMOCESPECIAL) FROM MRL_PROMOCESPECIALHIST C) + + ROWNUM + 1000000 SEQPROMOCESPECIAL,
       PLU,
       1 QTDEMBALAGEM,
       LOJA NROEMPRESA,
       NULL CODACESSOESPECIAL, --(SELECT NAG_GERA_EAN13_AUTO(LOJA) AS EAN FROM DUAL) CODACESSOESPECIAL,
       ROUND(
       TRUNC(
            S.PRECOVALIDNORMAL -
            ((C.PERC_DESCONTO/100) * S.PRECOVALIDNORMAL)
       , 1) + 0.09, 2) VLRPRECOPROMOC,
       QTDE_REBAIXA QTDESOLICITADA,
       0 QTDEETIQEMITIDA,
       DATA_ATIVIDADE DTAINICIO,
       DATA_VALIDADE DTAFIM,
       'P' STATUS,
       'IMPORTACAO APP GESTAO LOJAS' MOTIVOACAOPROMOC,
       DATA_ATIVIDADE DTAHORALTERACAO,
       'AUTOMATICO' USUALTERACAO,
       NULL DTAHORAPROVACAO,
       NULL USUAPROVACAO,
       NULL MOTIVOREPROVA,
       NULL INDLIBERACAO,
       NULL USULIBERACAO,
       NULL DTAHORALIBERACAO,
       NULL INDEMIETIQUETA,
       NULL SEQPROMOCESPECIALORIGEM,
       NULL INDREPLICAFAMILIA,
       NULL INDREPLICAASSOCIADO,
       NULL INDREPLICARELACIONADO

       FROM NAGV_APP_DATAVALIDADE@CONSINCODW A  INNER JOIN MAX_EMPRESA M ON M.NROEMPRESA = A.LOJA
                                                INNER JOIN MRL_PRODEMPSEG S ON S.SEQPRODUTO = A.PLU AND S.NROEMPRESA = M.NROEMPRESA AND S.NROSEGMENTO = M.NROSEGMENTOPRINC AND S.QTDEMBALAGEM = 1
                                                INNER JOIN MAP_PRODUTO P ON P.SEQPRODUTO = A.PLU
                                                INNER JOIN NAGV_DESCCATEG_DATA_APP C ON C.SEQFAMILIA = P.SEQFAMILIA

 WHERE 1=1

   AND DATA_ATIVIDADE >= TRUNC(SYSDATE) - 3
   AND QTDE_REBAIXA >= 0
   AND C.CATEGORIAN1 != 'FRIOS E LATICINIOS'
   -- Inicial apenas det lojas
   AND A.LOJA IN (14,50,57)
;
