CREATE OR REPLACE VIEW NAGV_BUSCADTAPEDIDO AS
SELECT DISTINCT SEQLOTEMODELO,
       TO_DATE(CONSINCO.NAGF_BUSCAULTDTAPEDIDO(X.SEQLOTEMODELO), 'DD/MM/YY') DATA_VALIDA,
       NVL(X.HORAMIN, '01:00') HORAMIN, X.DIASEMANA, X.ASSISTENTE, X.DIASCONFIG, X.EMAIL_FORNEC, FORMACALC, X.UTIL_SL_CD

  FROM CONSINCO.NAGT_CONTROLELOTECOMPRA X
 WHERE CONSINCO.NAGF_BUSCAULTDTAPEDIDO(X.SEQLOTEMODELO) IS NOT NULL

  ORDER BY 2 ASC, 3;
