CREATE OR REPLACE VIEW NAGV_BASE_MN_ENCARTE AS

SELECT X.SEQENCARTE, 
       SUBSTR(X.SEQENCARTE||'/'||CASE WHEN M.NROEMPRESA = 54 THEN 'NAG SP' ELSE DECODE(M.NROSEGMENTOPRINC, 2, 'NAG SP', 4, 'MIXTER', 3, 'RIO') END||' - '||
       TO_CHAR(NVL(P.DTAVIGENCIAINI,X.DTAINICIO),'DD')||' a '||TO_CHAR(NVL(P.DTAVIGENCIAFIM,X.DTAFIM), 'DD')||' - '||NVL(J.NOMEJANELA,X.DESCRICAO),0,79) DESC_PROMOC,
       NVL(P.DTAVIGENCIAINI,X.DTAINICIO) DTAINICIO, NVL(P.DTAVIGENCIAFIM,X.DTAFIM) DTAFIM,
       E.NROEMPRESA, CASE WHEN M.NROEMPRESA = 54 THEN 2 ELSE M.NROSEGMENTOPRINC END NROSEGMENTO, P.SEQPRODUTO, C.PRECOCARTAO PRECO_MN, P.SEQORDEM, SEQFAMILIA, S.SEQSIMILARIDADE

  FROM MRL_ENCARTE X INNER JOIN MRL_ENCARTEPRODUTO P ON P.SEQENCARTE = X.SEQENCARTE
                     INNER JOIN MRL_ENCARTEPRODUTOPRECO C ON C.SEQPRODUTO = P.SEQPRODUTO AND X.SEQENCARTE = C.SEQENCARTE
                     INNER JOIN MRL_ENCARTEEMP E ON E.SEQENCARTE = X.SEQENCARTE
                     INNER JOIN MAX_EMPRESA M ON M.NROEMPRESA = E.NROEMPRESA AND C.NROAGRUPAMENTO = CASE WHEN M.NROEMPRESA = 54 THEN 2 ELSE M.NROSEGMENTOPRINC END -- 54 considerada como Nagumo SP
                     INNER JOIN MAP_PRODUTO PR ON PR.SEQPRODUTO = P.SEQPRODUTO
                      LEFT JOIN MRL_ENCARTEJANELA J ON J.SEQENCARTE = X.SEQENCARTE AND J.SEQJANELA = P.SEQJANELA AND J.NROPAGINA = P.NROPAGINA
                      LEFT JOIN MAP_PRODSIMILAR S ON S.SEQPRODUTO = PR.SEQPRODUTO 

 WHERE 1=1
   AND C.PRECOCARTAO > 0
;
