CREATE OR REPLACE VIEW NAGV_INFNUTRIC_PIVOT_V4 AS
SELECT SEQINFNUTRIC,
       QTDPORCAO,
       VE_PORCAO, ROUND(VE_PORCAO * 100 / QTDPORCAO, 2) VE_100G, VE_VD,
       C_PORCAO,  ROUND(C_PORCAO  * 100 / QTDPORCAO, 2) C_100G,  C_VD,
       AT_PORCAO, ROUND(AT_PORCAO * 100 / QTDPORCAO, 2) AT_100G, AT_VD,
       AA_PORCAO, ROUND(AA_PORCAO * 100 / QTDPORCAO, 2) AA_100G, AA_VD,
       P_PORCAO,  ROUND(P_PORCAO  * 100 / QTDPORCAO, 2) P_100G,  P_VD,
       GT_PORCAO, ROUND(GT_PORCAO * 100 / QTDPORCAO, 2) GT_100G, GT_VD,
       GS_PORCAO, ROUND(GS_PORCAO * 100 / QTDPORCAO, 2) GS_100G, GS_VD,
       GR_PORCAO, ROUND(GR_PORCAO * 100 / QTDPORCAO, 2) GR_100G, GR_VD,
       FA_PORCAO, ROUND(FA_PORCAO * 100 / QTDPORCAO, 2) FA_100G, FA_VD,
       SO_PORCAO, ROUND(SO_PORCAO * 100 / QTDPORCAO, 2) SO_100G, SO_VD
FROM (
    SELECT N.SEQINFNUTRIC,
           N.QTDPORCAO,
           A.LISTA,
           TO_NUMBER(REPLACE(B.DESCQTDPORCAO, ',', '.')) DESCQTDPORCAO,  -- << ajustar aqui quando souber as casas decimais
           B.PERCVLRDIAREF
    FROM MAP_INFNUTRIC N
    INNER JOIN MAP_INFNUTRICTAB B ON B.SEQINFNUTRIC = N.SEQINFNUTRIC
    INNER JOIN MAX_ATRIBUTOFIXO A ON A.SEQATRIBUTOFIXO = B.SEQATRIBUTOFIXO
                                  AND A.TIPATRIBUTOFIXO = 'INFNUTRIC'
)
PIVOT (
    MAX(DESCQTDPORCAO) AS PORCAO,
    MAX(PERCVLRDIAREF) AS VD
    FOR LISTA IN (
        'VE' AS VE, 'C' AS C, 'AT' AS AT, 'AA' AS AA, 'P' AS P,
        'GT' AS GT, 'GS' AS GS, 'GR' AS GR, 'FA' AS FA, 'SO' AS SO
    )
)
;
